structure:
structure_generate:
    name: GPT_ONLY
    #ChoreoGrapher Configs
    ckpt_epoch: 29
    base:
        embd_pdrop: 0.1
        resid_pdrop: 0.1
        attn_pdrop: 0.1
#        vocab_size_up: 512
        vocab_size_up: 45
        vocab_size_down: 27
        block_size: 29
        n_layer: 6
        n_head: 12
        n_embd: 768
        n_music: 438
        n_music_emb: 768
    head:
        embd_pdrop: 0.1
        resid_pdrop: 0.1
        attn_pdrop: 0.1
        vocab_size: 512
        block_size: 29
        n_layer: 6
        n_head: 12
        n_embd: 768
        vocab_size_up: 512
        vocab_size_down: 512
    n_music: 438
    n_music_emb: 768
    joint_channel: 3
    block_size: 29

loss_weight:
    mse_weight: 1
optimizer:
    type: Adam
    kwargs:
        lr: 0.00005
        betas: [0.5, 0.999]
        weight_decay: 0
    schedular_kwargs:
        milestones: [250, 400]
        gamma: 0.1
# schedular: []
data:
    name: aist
    train_dir: data/aistpp_train_wav
    test_dir: data/aistpp_test_full_wav
    seq_len: 240
    data_type: None
testing:
    height: 540
    width: 960
    ckpt_epoch: 360


#vqvae_weight: 'experiments/sep_vqvae_root/ckpt/epoch_500.pt'
init_weight: 'experiments/motion_gpt_only_2/ckpt/epoch_200.pt'
expname: motion_gpt_only_2


need_not_train_data: True
#need_not_test_data: True

epoch: 400
batch_size: 32
# demo: True
save_per_epochs: 20
test_freq: 40
log_per_updates: 1
seed: 42
joint_channel: 3
rotmat: False
cuda: True
global_vel: False
ds_rate: 1
move: 8
#external_wav: data/aistpp_music_feat_7.5fps
external_wav_rate: 1
# random_init_test: True
music_normalize: False
# demo: False
# sample_code_length: 150
# analysis_array: [438, 511, 419, 11, 7, 92, 128, 256, 333]
